apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
  - name: nginx-prem
    image: nginx:1.21
    ports:
    - containerPort: 8080
  - name: watcher-prem
    image: afakharany/watcher
